### ISSUE TITLE
Prototypes

### ISSUE THREAD

**Issue by twifty** [paazmaya/yaml-validator#17]
I was so hoping this would fit into my project, but I can't see, either in your readme or tests, if it supports a prototype schema.

Given the following yaml:
```yaml
app:
  services:
    foo:
        verb: "Give"
        quantifier: 10
        noun: "slaps"
    bar:
        verb: "Accept"
        quantifier: "any"
        noun: "women"
```
Each `service` must conform to the same schema, but it's unknown how many there are or what keys they will use.

Looking at the sources, I don't believe it is possible to read the file myself and apply a schema against an existing object. If it were, I could have done a multi stage validation.
