### ISSUE TITLE
dynamic key support?

### ISSUE THREAD

**Issue by truongln88** [paazmaya/yaml-validator#19]
Does yaml-validator support dynamic keys? I have object with the following structure:

```yaml
dynamicKey1:
  staticKeyA: value
  staticKeyB: value
dynamicKey2:
  staticKeyA: value
  staticKeyB: value
...
```

Is it possible to check this structure?

I know I can convert the data model to:

```yaml
- name: dynamicKey1
  staticKeyA: value
  staticKeyB: value
- name: dynamicKey2
  staticKeyA: value
  staticKeyB: value
...
```

then it's easy to be validated. But changing the data model introduces cost.
